"""
Pydantic Schemas Package

Request/Response schemas for API validation.
"""

# Auth schemas
from .auth import (
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    PasswordChangeRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    Token,
    TokenData,
    TokenRefresh,
)

# Calendar schemas
from .calendar import (
    CalendarBase,
    CalendarListResponse,
    CalendarResponse,
    CalendarStatsResponse,
    CalendarViewRequest,
    EventAttendeeRequest,
    EventAttendeeResponse,
    EventAttendeeResponseUpdate,
    EventBase,
    EventDashboardResponse,
    EventListResponse,
    EventResponse,
    EventSearchRequest,
    EventType,
    RecurrenceType,
    RecurringEventResponse,
)

# Common schemas
from .common import (
    ActivityLogEntry,
    ActivityLogResponse,
    Address,
    BulkOperationRequest,
    BulkOperationResponse,
    ContactInfo,
    Coordinates,
    DateRangeFilter,
    ErrorResponse,
    ExportRequest,
    ExportResponse,
    FileUploadResponse,
    FilterParams,
    HealthCheckResponse,
    ImportRequest,
    ImportResponse,
    Metadata,
    NotificationPreferences,
    PaginatedResponse,
    PaginationParams,
    SearchParams,
    SortParams,
    StatsResponse,
    SuccessResponse,
    SystemInfoResponse,
    TimeRange,
    ValidationErrorResponse,
)

# Project schemas
from .project import (
    ProjectAttachmentResponse,
    ProjectBase,
    ProjectCommentBase,
    ProjectCommentResponse,
    ProjectDashboardResponse,
    ProjectListResponse,
    ProjectMemberBase,
    ProjectMemberResponse,
    ProjectMemberRole,
    ProjectPriority,
    ProjectResponse,
    ProjectSearchRequest,
    ProjectStatsResponse,
    ProjectStatus,
)

# Task schemas
from .task import (
    TagBase,
    TagResponse,
    TagUpdate,
    TaskAssignmentResponse,
    TaskAssignRequest,
    TaskAttachmentResponse,
    TaskBase,
    TaskCommentBase,
    TaskCommentResponse,
    TaskDashboardResponse,
    TaskGanttResponse,
    TaskListResponse,
    TaskPriority,
    TaskResponse,
    TaskSearchRequest,
    TaskStatsResponse,
    TaskStatus,
    TaskTimeLogBase,
    TaskTimeLogResponse,
    TaskType,
)

# User schemas
from .user import (
    UserActivityLogResponse,
    UserBase,
    UserCreateRequest,
    UserEmailVerification,
    UserListResponse,
    UserLoginRequest,
    UserLoginResponse,
    UserPasswordChangeRequest,
    UserPasswordReset,
    UserPasswordResetConfirm,
    UserProfileUpdateRequest,
    UserPublic,
    UserRefreshToken,
    UserResponse,
    UserRole,
    UserSessionResponse,
    UserStatsResponse,
    UserStatus,
    UserUpdateRequest,
)

__all__ = [
    # Auth schemas
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "PasswordChangeRequest",
    "PasswordResetConfirm",
    "PasswordResetRequest",
    "Token",
    "TokenData",
    "TokenRefresh",
    # Calendar schemas
    "CalendarBase",
    "CalendarCreateRequest",
    "CalendarListResponse",
    "CalendarResponse",
    "CalendarStatsResponse",
    "CalendarUpdateRequest",
    "CalendarViewRequest",
    "EventAttendeeRequest",
    "EventAttendeeResponse",
    "EventAttendeeResponseUpdate",
    "EventBase",
    "EventCreateRequest",
    "EventDashboardResponse",
    "EventListResponse",
    "EventResponse",
    "EventSearchRequest",
    "EventType",
    "EventUpdateRequest",
    "RecurringEventResponse",
    "RecurrenceType",
    # Common schemas
    "ActivityLogEntry",
    "ActivityLogResponse",
    "Address",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "ContactInfo",
    "Coordinates",
    "DateRangeFilter",
    "ErrorResponse",
    "ExportRequest",
    "ExportResponse",
    "FileUploadResponse",
    "FilterParams",
    "HealthCheckResponse",
    "ImportRequest",
    "ImportResponse",
    "Metadata",
    "NotificationPreferences",
    "PaginatedResponse",
    "PaginationParams",
    "SearchParams",
    "SortParams",
    "StatsResponse",
    "SuccessResponse",
    "SystemInfoResponse",
    "TimeRange",
    "ValidationErrorResponse",
    # Project schemas
    "ProjectAttachmentResponse",
    "ProjectBase",
    "ProjectCommentBase",
    "ProjectCommentCreateRequest",
    "ProjectCommentResponse",
    "ProjectCommentUpdateRequest",
    "ProjectCreateRequest",
    "ProjectDashboardResponse",
    "ProjectListResponse",
    "ProjectMemberBase",
    "ProjectMemberCreateRequest",
    "ProjectMemberResponse",
    "ProjectMemberRole",
    "ProjectMemberUpdateRequest",
    "ProjectPriority",
    "ProjectResponse",
    "ProjectSearchRequest",
    "ProjectStatus",
    "ProjectStatsResponse",
    "ProjectUpdateRequest",
    # Task schemas
    "TagBase",
    "TagCreateRequest",
    "TagResponse",
    "TagUpdate",
    "TaskAssignmentResponse",
    "TaskAssignRequest",
    "TaskAttachmentResponse",
    "TaskBase",
    "TaskCommentBase",
    "TaskCommentCreateRequest",
    "TaskCommentResponse",
    "TaskCommentUpdateRequest",
    "TaskCreateRequest",
    "TaskDashboardResponse",
    "TaskGanttChartResponse",
    "TaskGanttResponse",
    "TaskKanbanBoardResponse",
    "TaskListResponse",
    "TaskPriority",
    "TaskResponse",
    "TaskSearchRequest",
    "TaskStatsResponse",
    "TaskStatus",
    "TaskTimeLogBase",
    "TaskTimeLogCreateRequest",
    "TaskTimeLogResponse",
    "TaskTimeLogUpdateRequest",
    "TaskType",
    "TaskUpdateRequest",
    # User schemas
    "UserActivityLogResponse",
    "UserBase",
    "UserCreateRequest",
    "UserEmailVerification",
    "UserListResponse",
    "UserLoginRequest",
    "UserLoginResponse",
    "UserPasswordChangeRequest",
    "UserPasswordReset",
    "UserPasswordResetConfirm",
    "UserProfileUpdateRequest",
    "UserPublic",
    "UserRefreshToken",
    "UserResponse",
    "UserRole",
    "UserSessionResponse",
    "UserStatsResponse",
    "UserStatus",
    "UserUpdateRequest",
]
