"""
Pydantic 스키마 패키지

API 검증을 위한 요청/응답 스키마들입니다.
"""

# 인증 스키마
from .auth import (
    AuthenticationError,
    EmailVerificationConfirm,
    EmailVerificationRequest,
    LoginRequest,
    LoginResponse,
    LoginUserResponse,
    LogoutRequest,
    OAuthLoginRequest,
    PasswordChangeRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterRequest,
    SessionInfo,
    Token,
    TokenData,
    TokenRefresh,
    TwoFactorAuthRequest,
    UserLoginHistory,
)

# 캘린더 스키마
from .calendar import (
    CalendarBase,
    CalendarCreateRequest,
    CalendarListResponse,
    CalendarResponse,
    CalendarStatsResponse,
    CalendarUpdateRequest,
    CalendarViewRequest,
    EventAttendeeRequest,
    EventAttendeeResponse,
    EventAttendeeResponseUpdate,
    EventBase,
    EventCreateRequest,
    EventDashboardResponse,
    EventListResponse,
    EventResponse,
    EventSearchRequest,
    EventUpdateRequest,
    RecurringEventResponse,
)

# 공통 스키마
from .common import (
    ActivityLogEntry,
    ActivityLogResponse,
    Address,
    BulkOperationRequest,
    BulkOperationResponse,
    ContactInfo,
    Coordinates,
    DateRangeFilter,
    ErrorResponse,
    ExportRequest,
    ExportResponse,
    FileUploadResponse,
    FilterParams,
    HealthCheckResponse,
    ImportRequest,
    ImportResponse,
    Metadata,
    NotificationPreferences,
    PaginatedResponse,
    PaginationParams,
    SearchParams,
    SortParams,
    StatsResponse,
    SuccessResponse,
    SystemInfoResponse,
    TimeRange,
    ValidationErrorResponse,
)

# 프로젝트 스키마
from .project import (
    ProjectAttachmentResponse,
    ProjectBase,
    ProjectCommentBase,
    ProjectCommentCreateRequest,
    ProjectCommentResponse,
    ProjectCommentUpdateRequest,
    ProjectCreateRequest,
    ProjectDashboardResponse,
    ProjectListResponse,
    ProjectMemberBase,
    ProjectMemberCreateRequest,
    ProjectMemberResponse,
    ProjectMemberUpdateRequest,
    ProjectResponse,
    ProjectSearchRequest,
    ProjectStatsResponse,
    ProjectUpdateRequest,
)

# 작업 스키마
from .task import (
    TagBase,
    TagCreateRequest,
    TagResponse,
    TaskAssignmentResponse,
    TaskAssignRequest,
    TaskAttachmentResponse,
    TaskBase,
    TaskCommentBase,
    TaskCommentCreateRequest,
    TaskCommentResponse,
    TaskCommentUpdateRequest,
    TaskCreateRequest,
    TaskDashboardResponse,
    TaskGanttChartResponse,
    TaskGanttResponse,
    TaskKanbanBoardResponse,
    TaskListResponse,
    TaskResponse,
    TaskSearchRequest,
    TaskStatsResponse,
    TaskTimeLogBase,
    TaskTimeLogCreateRequest,
    TaskTimeLogResponse,
    TaskTimeLogUpdateRequest,
    TaskUpdateRequest,
)

# 사용자 스키마
from .user import (
    UserActivityLogResponse,
    UserBase,
    UserCreateRequest,
    UserEmailVerification,
    UserListResponse,
    UserLoginRequest,
    UserLoginResponse,
    UserPasswordChangeRequest,
    UserPasswordReset,
    UserPasswordResetConfirm,
    UserProfileUpdateRequest,
    UserPublic,
    UserRefreshToken,
    UserResponse,
    UserSessionResponse,
    UserStatsResponse,
    UserUpdateRequest,
)

__all__ = [
    # 인증 스키마
    "AuthenticationError",
    "EmailVerificationConfirm",
    "EmailVerificationRequest",
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "OAuthLoginRequest",
    "PasswordChangeRequest",
    "PasswordResetConfirm",
    "PasswordResetRequest",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RegisterRequest",
    "SessionInfo",
    "Token",
    "TokenData",
    "TokenRefresh",
    "TwoFactorAuthRequest",
    "UserLoginHistory",
    "LoginUserResponse",
    # 캘린더 스키마
    "CalendarBase",
    "CalendarCreateRequest",
    "CalendarListResponse",
    "CalendarResponse",
    "CalendarStatsResponse",
    "CalendarUpdateRequest",
    "CalendarViewRequest",
    "EventAttendeeRequest",
    "EventAttendeeResponse",
    "EventAttendeeResponseUpdate",
    "EventBase",
    "EventCreateRequest",
    "EventDashboardResponse",
    "EventListResponse",
    "EventResponse",
    "EventSearchRequest",
    "EventUpdateRequest",
    "RecurringEventResponse",
    # 공통 스키마
    "ActivityLogEntry",
    "ActivityLogResponse",
    "Address",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "ContactInfo",
    "Coordinates",
    "DateRangeFilter",
    "ErrorResponse",
    "ExportRequest",
    "ExportResponse",
    "FileUploadResponse",
    "FilterParams",
    "HealthCheckResponse",
    "ImportRequest",
    "ImportResponse",
    "Metadata",
    "NotificationPreferences",
    "PaginatedResponse",
    "PaginationParams",
    "SearchParams",
    "SortParams",
    "StatsResponse",
    "SuccessResponse",
    "SystemInfoResponse",
    "TimeRange",
    "ValidationErrorResponse",
    # 프로젝트 스키마
    "ProjectAttachmentResponse",
    "ProjectBase",
    "ProjectCommentBase",
    "ProjectCommentCreateRequest",
    "ProjectCommentResponse",
    "ProjectCommentUpdateRequest",
    "ProjectCreateRequest",
    "ProjectDashboardResponse",
    "ProjectListResponse",
    "ProjectMemberBase",
    "ProjectMemberCreateRequest",
    "ProjectMemberResponse",
    "ProjectMemberUpdateRequest",
    "ProjectResponse",
    "ProjectSearchRequest",
    "ProjectStatsResponse",
    "ProjectUpdateRequest",
    # 작업 스키마
    "TagBase",
    "TagCreateRequest",
    "TagResponse",
    "TaskUpdateRequest",
    "TaskAssignmentResponse",
    "TaskAssignRequest",
    "TaskAttachmentResponse",
    "TaskBase",
    "TaskCommentBase",
    "TaskCommentCreateRequest",
    "TaskCommentResponse",
    "TaskCommentUpdateRequest",
    "TaskCreateRequest",
    "TaskDashboardResponse",
    "TaskGanttChartResponse",
    "TaskGanttResponse",
    "TaskKanbanBoardResponse",
    "TaskListResponse",
    "TaskResponse",
    "TaskSearchRequest",
    "TaskStatsResponse",
    "TaskTimeLogBase",
    "TaskTimeLogCreateRequest",
    "TaskTimeLogResponse",
    "TaskTimeLogUpdateRequest",
    "TaskUpdateRequest",
    # 사용자 스키마
    "UserActivityLogResponse",
    "UserBase",
    "UserCreateRequest",
    "UserEmailVerification",
    "UserListResponse",
    "UserLoginRequest",
    "UserLoginResponse",
    "UserPasswordChangeRequest",
    "UserPasswordReset",
    "UserPasswordResetConfirm",
    "UserProfileUpdateRequest",
    "UserPublic",
    "UserRefreshToken",
    "UserSessionResponse",
    "UserStatsResponse",
    "UserUpdateRequest",
    "UserResponse",
]
